# Generated by Django 5.1.3 on 2026-05-17 20:45

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('level_min', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('level_max', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='C2', max_length=2)),
                ('story_type', models.CharField(choices=[('narrative', 'Narrative'), ('dialog', 'Dialog'), ('news', 'News'), ('business', 'Business'), ('academic', 'Academic')], default='narrative', max_length=20)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('estimated_read_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='languages.language')),
                ('tags', models.ManyToManyField(blank=True, to='stories.storytag')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StoryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_type', models.CharField(choices=[('original', 'Original'), ('present', 'Present Tense'), ('past', 'Past Tense'), ('future', 'Future Tense'), ('native', 'Native Speaker'), ('dialog', 'Dialog Form'), ('idioms', 'Idioms Highlighted'), ('emotional', 'Emotional Tone'), ('vocabulary', 'Vocabulary Focus'), ('qa', 'Q&A Format')], max_length=20)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version_read', models.CharField(blank=True, max_length=20)),
                ('versions_read', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('quiz_best_score', models.IntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['slug'], name='stories_sto_slug_b9091c_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['language', 'is_published'], name='stories_sto_languag_abbc2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyversion',
            unique_together={('story', 'version_type')},
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'story')},
        ),
        migrations.AlterUniqueTogether(
            name='userstoryprogress',
            unique_together={('user', 'story')},
        ),
    ]
