# Generated by Django 5.1.3 on 2026-05-20 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('stories', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(blank=True, max_length=20)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('translation', models.CharField(max_length=200)),
                ('synonyms', models.JSONField(default=list)),
                ('romanization', models.CharField(blank=True, max_length=200)),
                ('audio_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='new', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('source_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.story')),
                ('source_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.word')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(blank=True, related_name='collections', to='notebook.userword')),
            ],
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'next_review_at'], name='notebook_us_user_id_71dd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'status'], name='notebook_us_user_id_4050c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('user', 'language', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='userwordcollection',
            unique_together={('user', 'name')},
        ),
    ]
