# Generated by Django 5.1.3 on 2026-05-17 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('idiom', 'Idiom')], default='noun', max_length=10)),
                ('definition', models.TextField()),
                ('romanization', models.CharField(blank=True, max_length=200)),
                ('audio_url', models.URLField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='StoryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_sentence', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_words', to='stories.story')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WordSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vocabulary.word')),
            ],
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language', 'word'], name='vocabulary__languag_aa5541_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('language', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='storyword',
            unique_together={('story', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='wordsynonym',
            unique_together={('word', 'synonym')},
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('word', 'target_language')},
        ),
    ]
